apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shoubhik-demo
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: shbose
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/redhat-appstudio-appdata/nyc-transit-shbose-roll-account.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
